const exampleScripts = [
  {
    name: "Zing",
    script: [
      "Mijn levenslied, is fantastisch, als het aankomt!",
      "Zing mijn levenslied!",
    ],
  },
  {
    name: "Flesjes",
    script: [
      "Je hart zegt flesjes bier op de muur",
      "Je ziel zegt flesjes bier",
      "Henk zegt Pak er eentje af, geef het door",
      "De biertjes waren echt-meer dan-nodig",
      "Zolang de biertjes niet weg zijn",
      "Zeg het met je hart",
      "zeg het met je ziel",
      "zeg Henk,",
      "Haal de biertjes neer",
      "zeg het met je hart",
    ],
  },
  {
    name: "FizzBuzz",
    script: [
      "De nacht neemt je hart en je ziel",
      "Zolang je hart zo hoog is als je ziel",
      "Stop je hart zonder je ziel in je hart",
      "",
      "Geef je hart terug",
      "",
      "Verlangen is aantoonbaar de-liefdes accepteren",
      "Mijn wereld is niets",
      "Vuur is gek",
      "Haat is water",
      "Totdat mijn wereld bestaat uit Verlangen",
      "Bouw mijn wereld op",
      "Als de nacht ontvangt mijn wereld, Vuur is niets en de nacht ontvangt mijn wereld, Haat is niets",
      'Roep "FizzBuzz!"',
      "Herbeleef",
      "",
      "Als de nacht ontvangt mijn wereld, Vuur niets is",
      'Schreeuw "Fizz!"',
      "Herbeleef",
      "",
      "Als de nacht ontvangt mijn wereld, Haat niets is",
      'Zeg "Buzz!"',
      "Herbeleef",
      "",
      "Fluister mijn wereld",
    ],
  },
  {
    name: "Febo-nacci",
    script: [
      "je honger bestaat uit aardappels!",
      "je snack bestaat uit frikadellen,",
      "je friet is weg?",
      "De klepjes zijn 15",
      "Zolang de klepjes niet weg zijn",
      "schreeuw je honger!",
      "stop je honger met je snack in je friet",
      "laat je honger je snack wezen",
      "laat je snack je friet wezen...",
      "Haal de klepjes neer!",
    ],
  },
];

export default exampleScripts;
